site_name: CDEvents CLI
site_description: A CLI tool for generating and sending CDEvents into CI/CD toolchains using CloudEvents as transport
site_author: brunseba
site_url: https://github.com/brunseba/cdevents-tools

repo_name: brunseba/cdevents-tools
repo_url: https://github.com/brunseba/cdevents-tools

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli-reference.md
  - Examples: examples.md
  - Docker: docker.md
  - Quality:
    - Quality Metrics: quality-metrics.md
    - Quality Report: quality/QUALITY_REPORT.md
    - Coverage Summary: quality/coverage-summary.md
    - Complexity Report: quality/complexity-report.md
    - Linting Report: quality/linting-report.md
    - Performance Metrics: quality/performance-metrics.md
  - Contributing: contributing.md
  - Development Standards: development-standards.md
  - License: LICENSE.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brunseba/cdevents-tools
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/brunseba
